version: '3.8'

services:
  billing-service:
    image: ghcr.io/eflynn01102/billing-service:latest
    container_name: billing-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped
    networks:
      - smart-meter-network

networks:
  smart-meter-network:
    driver: bridge
