FROM oven/bun:latest as build-stage

WORKDIR /app

COPY ./apps/client/package*.json ./
RUN bun install
COPY ./ .
RUN bun run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY ./docker/nginx.conf /etc/nginx/nginx.conf
